Modify sim reco func
next-exp/ANTEA pull request #60
Opened 2021-04-19 14:57 UTC by carmenromo

A simple change has been introduced in order to avoid saving in the hdf5 tables the non-passing-threshold events.

Note that when you'd call this function event, you should make a condition like this:
```
df = simulate_reco_event(...)
if df is None:
    continue (for example)
```
The statement: `if df == None:` will fail!

2021-04-20 07:38 UTC, paolafer commented
I've realized we don't have tests for this function. Could you add some for this modification, for instance? In another PR we should also add the script to simulate fastsim in the script folder.

2021-04-20 09:10 UTC, carmenromo commented
> I've realized we don't have tests for this function. Could you add some for this modification, for instance? In another PR we should also add the script to simulate fastsim in the script folder.

Sure! I take care of them!

2021-04-21 07:30 UTC, paolafer commented on antea/mcsim/fastmc3d.py
> +                           'reco_t2':     t2_reco}, index=[0])
I understand that using `index=[0]` in this function implies that in the resulting dataframe that we build all the rows have the same index, is that correct? If that's the case, I would make the index an argument of the function itself, in that case we can call the function with an ascending number and have a dataframe with proper index as a result. What do you think?

2021-04-21 08:16 UTC, carmenromo commented on antea/mcsim/fastmc3d.py
> +                           'reco_t2':     t2_reco}, index=[0])
Yes, you are right, I have read that `index=[0]` would set the starting index to 0, and `index=[1]` to 1 for example, but in practice, since we are passing one line of the table at a time, all the indexes would be 0. In fact, this was the index we were passing with the previous code, since we were creating a one line dataframe for event and we were doing it passing a one element list, so every time it took 0 as index, too. I am not sure if this is very relevant for us, since what we care is the `event_id`, but I can implement what you say!

2021-04-21 08:19 UTC, paolafer commented on antea/mcsim/fastmc3d.py
> +                           'reco_t2':     t2_reco}, index=[0])
I see. We haven't used the index so far, so maybe it's not that relevant. One can always re-index the resulting dataframe in the end, if needed, and maybe using `event_id` as index, instead. You can leave it as it is, then.

2021-04-22 08:00 UTC, paolafer requested changes
I would also change the name of the test file to something related to fastsim, since this is a new file added precisely for this test.

2021-04-22 08:08 UTC, paolafer commented on antea/mcsim/fastmc3d_test.py
> +        pos1, pos2, t1, t2, phot1, phot2 = rf.find_first_interactions_in_active(evt_parts, evt_hits, photo_range=1.)
Since you specify the value of `photo_range` here, I would do the same in the `simulate_reco_event` function.

2021-04-23 15:06 UTC, carmenromo commented on antea/mcsim/fastmc3d_test.py
> +            assert evt_df0 is None
Done!

2021-04-23 15:07 UTC, carmenromo commented on antea/mcsim/fastmc3d_test.py
> +        pos1, pos2, t1, t2, phot1, phot2 = rf.find_first_interactions_in_active(evt_parts, evt_hits, photo_range=1.)
Done!

2021-04-26 08:19 UTC, paolafer approved these changes
This PR simplifies the code, avoiding writing an empty row in the dataframe and adds a due test. Approved!

2021-04-26 08:19 UTC, merged