Functions for data analysis
next-exp/ANTEA pull request #72
Opened 2021-11-02 14:45 UTC by carmenromo

Some functions are included in order to perform data analysis of the PetBox detector. The three important functions perform the following cuts:
- Compute coincidences --> events with touched sensors in both planes (detection and coincidence).
- Events with max charge at center (either in the detection plane or either in the coincidence one).
- "Fully contained" events --> events that exclude the outer ring of sensors for the detection plane.

2021-11-15 12:05 UTC, paolafer commented
I would not create a new folder, because these functions are reconstruction functions, so I would use the already existing `reco` folder. I would modify the name of the file to `data_reco_functions`, which is more direct and it makes a parallelism with the `reco_functions` we use for MC. In a later PR we could maybe modify also the name of MC functions to mc_reco_functions. What do you think?

2021-11-15 12:06 UTC, paolafer commented
For some reason, it seems to me that you have duplicated the existing tests of `reco_functions`, can you correct it?

2021-11-15 12:08 UTC, carmenromo commented
> I would not create a new folder, because these functions are reconstruction functions, so I would use the already existing `reco` folder. I would modify the name of the file to `data_reco_functions`, which is more direct and it makes a parallelism with the `reco_functions` we use for MC. In a later PR we could maybe modify also the name of MC functions to mc_reco_functions. What do you think?

Yeah, that makes sense.

2021-11-15 12:09 UTC, carmenromo commented
> For some reasons, it seems to me that you have duplicated the existing tests of `reco_functions`, can you correct it?

Ups, sorry about that!

2021-11-15 13:18 UTC, paolafer commented
Now all the tests have disappeared. I understand that you still need to add the corresponding tests, right?

2021-11-15 13:28 UTC, carmenromo commented
Yes, I should add them.

2021-11-15 14:00 UTC, paolafer requested changes

2021-11-15 14:00 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +def select_evts_with_max_charge_at_center(df: pd.DataFrame,
If we want to keep the two functions `filter...` and `select...` I would call them in a more different way to differentiate them clearly. The former could be `is_max_charge_at_center`, since it is not actually a filter and returns booleans (the answer to "is..?"). It's just an idea, if you others, please propose.

2021-11-15 14:00 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +def filter_covered_evt(df: pd.DataFrame, min_sns: int = 2) -> bool:
Same as above: maybe the function can be called `is_event_contained`.

2021-11-15 14:00 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +int_area = [22, 23, 24, 25, 26, 27, 32, 33, 34, 35, 36, 37, 42, 43, 44, 45, 46, 47, 52, 53, 54, 55, 56, 57, 62, 63, 64, 65, 66, 67, 72, 73, 74, 75, 76, 77]
This line is too long, please reduce it.

2021-11-15 14:00 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +    df = df[df.tofpet_id == 0] ## Detection plane
Why in this function you don't leave the possibility of choosing the coincidence plane? Since you do it in the first function, I would do it here, as well. Alternatively, if we think we will never use this function in the coincidence plane, I would put it in the name of the function (`is_event_contained_in_det_plane` or something similar).

2021-11-15 14:00 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +def filter_covered_evt(df: pd.DataFrame, min_sns: int = 2) -> bool:
Why are you asking for a minimum number of SiPMs in this function? I'd say this is another filter.

2021-11-15 14:00 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +        return set(sens_unique).issubset(set(int_area))
I don't understand this assertion: it is `True` if all the sensors of an event are a subset of the list above, but we want that the function returns `True` if no sensor IDs are in the list above, right? I'm confused.

2021-11-16 15:33 UTC, carmenromo commented on antea/reco/data_reco_functions.py
> +def select_evts_with_max_charge_at_center(df: pd.DataFrame,
Yes, I like the idea!

2021-11-16 15:36 UTC, carmenromo commented on antea/reco/data_reco_functions.py
> +    df = df[df.tofpet_id == 0] ## Detection plane
Mmm I'm not sure if it makes sense for the coincidence plane, since there are only a few sensors and even for the det plane it is a very strict filter... I think I would do what you propose of calling the function `is_event_contained_in_det_plane `.

2021-11-16 16:01 UTC, carmenromo commented on antea/reco/data_reco_functions.py
> +def filter_covered_evt(df: pd.DataFrame, min_sns: int = 2) -> bool:
I thought that an event with only one sensor touched was not giving us much information...

2021-11-16 16:02 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +def filter_covered_evt(df: pd.DataFrame, min_sns: int = 2) -> bool:
But that's a choice of the analysis, it shouldn't be included in another filter.

2021-11-16 16:05 UTC, carmenromo commented on antea/reco/data_reco_functions.py
> +def filter_covered_evt(df: pd.DataFrame, min_sns: int = 2) -> bool:
Ok, but then would you remove the argument `min_sns`? Or just let the default value `min_sns` = 1?

2021-11-16 16:08 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +def filter_covered_evt(df: pd.DataFrame, min_sns: int = 2) -> bool:
I would remove it completely, it is another filter, which can be applied in the analysis, but doesn't belong to this function.

2021-11-16 16:15 UTC, carmenromo commented on antea/reco/data_reco_functions.py
> +        return set(sens_unique).issubset(set(int_area))
No, the list above contains the sensor ids of the internal area, not the external corona.

2021-11-16 16:18 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +        return set(sens_unique).issubset(set(int_area))
Alright, then!

2021-11-25 11:26 UTC, paolafer commented on antea/reco/data_reco_functions.py
> +        central_sns = [44, 45, 54, 55]
If you define `central_sns_det` and `central_sns_coinc` outside the function (the same you do for `int_area` and `corona`), you can use them in the `test_select_evts_with_max_charge_at_center` test without the need of redefining them.

2021-11-25 11:27 UTC, paolafer commented on antea/reco/data_reco_functions_test.py
> +corona = [11, 12, 13, 14, 15, 16, 17, 18, 21, 28, 31, 38, 41, 48,
You don't need to redefine it here, since it's already in `data_reco_functions.py`.

2021-11-25 11:34 UTC, paolafer commented on antea/reco/data_reco_functions_test.py
> +def test_select_evts_with_max_charge_at_center(ANTEADATADIR, det_plane, variable, tot_mode):
I have a problem with this test. I have tried to change the values of `central_sns` in the `is_max_charge_at_center` function to completely different values ([66, 67, 68]) and I would have expected the test to fail, but it doesn't. Can you reproduce it?

2021-11-25 11:38 UTC, carmenromo commented on antea/reco/data_reco_functions.py
> +        central_sns = [44, 45, 54, 55]
Ah, right!

2021-11-25 11:38 UTC, carmenromo commented on antea/reco/data_reco_functions_test.py
> +corona = [11, 12, 13, 14, 15, 16, 17, 18, 21, 28, 31, 38, 41, 48,
Done!

2021-11-25 13:16 UTC, paolafer commented on antea/reco/data_reco_functions_test.py
> +def test_select_evts_with_max_charge_at_center(ANTEADATADIR, det_plane, variable, tot_mode):
Solved.

2021-11-25 16:51 UTC, paolafer commented on antea/reco/data_reco_functions_test.py
> +def test_select_evts_with_max_charge_at_center(ANTEADATADIR, det_plane, variable, tot_mode):
Taking inspiration from this non-issue, I was thinking that maybe an additional test would be that `len(df_center)` is always grater than zero.

2021-11-26 10:27 UTC, carmenromo commented on antea/reco/data_reco_functions_test.py
> +def test_select_evts_with_max_charge_at_center(ANTEADATADIR, det_plane, variable, tot_mode):
Nice! I added it as an assert inside the test. Did you mean that, right? Better than create a new test.

2021-11-29 14:33 UTC, paolafer commented on antea/reco/data_reco_functions_test.py
> +def test_select_evts_with_max_charge_at_center(ANTEADATADIR, det_plane, variable, tot_mode):
Yes!

2021-11-29 14:34 UTC, paolafer approved these changes
The first functions to be used in data analysis have been added, with the corresponding tests. Approved!

2021-11-29 14:34 UTC, merged